app/models.py
from app import db, login 
from flask_login import UserMixin 
from datetime import datetime as dt
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String)
    last_name = db.Column(db.String)
    email = db.Column(db.String, unique=True, index=True)
    password = db.Column(db.String)
    created_on= db.Column(db.DateTime, default=dt.utcnow)
    icon = db.Column(db.Integer)

    def __repr__(self):
        return f'<User: {self.email} | {self.id}>'

    def __str__(self):
        return f'<User: {self.email} | {self.first_name} {self.last_name}>'

    def hash_password(self, original_password):
        return generate_password_hash(original_password)
    
    def check_hashed_password(self, login_password):
        return check_password_hash(self.password, login_password)

    def from_dict(self,data):
        self.first_name=data['first_name']
        self.last_name=data['last_name']
        self.email=data['email']
        self.password=self.hash_password(data['password'])
        self.icon = data['icon']

    def save(self):
        db.session.add(self) 
        db.session.commit()

    def get_icon_url(self):
        return f'https://avatars.dicebear.com/api/croodles/{self.icon}.svg'

@login.user_loader
def load_user(id):
    return User.query.get(int(id)) 

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager


#initializing plugins
login = LoginManager()

#init my database manager
db = SQLAlchemy()
migrate = Migrate()


def create_app(config_class=Config):
    #init the app
    app = Flask(__name__)
    #link in the config 
    app.config.from_object(config_class)
    
    #register plugins
    login.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    
    
    login.login_view='auth.login'
    login.login_message = 'You must login to continue'
    login.login_message_category = 'warning'

    from .blueprints.main import bp as main_bp
    app.register_blueprint(main_bp)

    from .blueprints.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    return app

app/blueprints/main/__init__.py
from flask import Blueprint

bp =Blueprint('main', __name__, url_prefix='')

from . import routes

app/blueprints/main/routes.py
from flask import render_template, request
import requests
from .import bp as main 
from ..auth.forms import PokemonForm
from flask_login import login_required

@main.route('/', methods = ['GET'])
@login_required
def index():
    return render_template('index.html.j2')

@main.route('/pokemon', methods=['GET', 'POST'])
@login_required
def pokemon():
    form = PokemonForm()
    if request.method == 'POST' and form.validate_on_submit():
        #do poke stuff
        poke = form.pokename.data
        url = f"https://pokeapi.co/api/v2/pokemon/{poke}"
        
        response = requests.get(url)
        if response.ok:
            poke = response.json()
            poke_dict={
                "poke_name":poke['name'],
                "attack_base_stat":poke ["stats"][1]["base_stat"],
                "hp_base_stat": poke["stats"][0]["base_stat"],
                "defense_base_stat": poke["stats"][2]["base_stat"],
                "front_shiny": poke["sprites"]["front_shiny"],
                "ability_name": poke["abilities"][0]["ability"]["name"],
                "base_experience": poke["base_experience"],
            }
        else:
            return "Please enter a valid Pokemon"
        
        return render_template('pokemon.html.j2', poke=poke_dict, form=form)
        
    return render_template('pokemon.html.j2', form=form)   

app/templates/base.html.j2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {# bootstrap css#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    {# global custom css#}
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
    
    <link rel="apple-touch-icon" sizes="180x180" href="{{url_for('static', filename='images/apple-touch-icon.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static', filename='images/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static', filename='images/favicon-16x16.png')}}">
    <link rel="manifest" href="{{url_for('static', filename='images/site.webmanifest')}}">


    {% block css %}

    {% endblock%}
    <title>Pokebook-{% block title %}{% endblock %}</title> 
</head>

<body>
    {% include './includes/nav.html.j2' %}
    
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for class, message in messages %}
                <div class="alert alert-{{class}} alert-dismissible fade show" role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    
    {% endwith %}
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
    
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

app/templates/includes/nav.html.j2
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div id= "nav-logo">
    <img src="{{url_for('static', filename='images/pokemon_logo.png')}}">
    </div>
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Pokebook</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-link" href="{{url_for('main.index')}}">Home</a>
                <a class="nav-link" href="{{url_for('main.pokemon')}}">Pokemon Info</a>
            

                {% else %}
                <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
                <a class="nav-link" href="{{url_for('auth.register')}}">Register</a>
                {% endif %}
            </div>
                {% if current_user.is_authenticated %}
                <ul class="navbar-nav ms-auto align-items-center">
                <a href='#'>
                    <img src="{{current_user.get_icon_url()}}" style="height:50px;">
                </a>
                <li class="nav-item"> 
                <div class="row">
                <div class="col-12">
                    <a class="nav-link" href="{{url_for('auth.edit_profile')}}"><i class="bi bi-pen-fill"></i></a>
                </div>
            
                <div class="col-12">
                    <a class="nav-link" href="{{url_for('auth.logout')}}"><i class="bi bi-door-closed-fill"></i></a>
                </div>
                </div>
            
                </li>
                </ul>
                {% endif %}
            
        </div>
    </div>
    </nav>

app/templates/index.html.j2
{% extends 'base.html.j2' %}
{% block title %}
  Welcome to Pokebook, search your pokemon!
{% endblock %}

{% block content %}
  <h1>Welcome to Pokebook, search your pokemon!</h1>
{% endblock %}

app/templates/login.html.j2
{% extends 'base.html.j2' %}
{% block title %}
Login
{% endblock %}

{% block content %}
<h1>Login</h1>
<form action="{{url_for('auth.login')}}" method = "POST">

  {{form.hidden_tag()}}
  <div>
  {{form.email.label(class="form-label")}}
  {{form.email(class="form-control")}}
  {% for error in form.email.errors %}
    <small style="color:red;">{{error}}</small>
  {% endfor %}
  </div>
  <br>
  <div>
  {{form.password.label(class="form-label")}}
  {{form.password(class="form-control")}}
  {% for error in form.password.errors %}
    <small style="color:red;">{{error}}</small>
  {% endfor %}
  </div>
  <div>
  {{form.submit(class="btn btn-primary form-control")}}
  </div>
</form>
{% endblock %}

app/templates/pokemon.html.j2
{% extends 'base.html.j2' %}
{% block title %}
Pokemon
{% endblock %}

{% block content %}

<h1>Pokemon Information</h1>
<form action="{{url_for('main.pokemon')}}" method="POST">
{{ form.hidden_tag()}}
<div>
{{form.pokename.label (class = "form-label")}}
{{form.pokename(class = "form-control")}}
</div>
<br>
      
      {#<div class="mb-3">
        <label for="poke" class="form-label">Pokemon Name</label>
        <input type="text" name="poke" class="form-control" id="poke">
      </div>#}
<div>
{{form.submit(class="btn btn-primary form-control")}}
</div>
</form>
{% if poke %}

  <table class="table table-striped table-hover table-dark">
    <thead>
      <tr>
        <th scope="col">Pokemon Name</th>
        <th scope="col">Attack Base</th>
        <th scope="col">HP Base</th>
        <th scope="col">Defense Base</th>
        <th scope="col">Ability</th>
        <th scope="col">Base Experience</th>
        <th scope="col">Image</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">{{poke['poke_name']}}</th>
        <td>{{poke.attack_base_stat}}</td>
        <td>{{poke.hp_base_stat}}</td>
        <td>{{poke.defense_base_stat}}</td>
        <td>{{poke.ability_name}}</td>
        <td>{{poke.base_experience}}</td>
        <td><img src={{poke.front_shiny}}></td>
      </tr>
    </tbody>
  </table>
{% endif %}

{% endblock %}

app/templates/register.html.j2
{% extends 'base.html.j2' %}
{% block title %}
  {% if current_user.is_authenticated %}
    Edit Profile
  {% else %}
      Register
  {% endif %}
{% endblock %}

{% block content %}
<h1>
  {% if current_user.is_authenticated %}
  Edit Profile
  {% else %}
  Register
  {% endif %}
</h1>
<form action="{{url_for('auth.edit_profile') if current_user.is_authenticated else url_for('auth.register')}}" method = "POST">

  {{form.hidden_tag()}}

  <div>
  {{form.icon.label(class="form-label")}}
  <div>
    {% for subfield in form.icon%}
    {{subfield}} 
    {{subfield.label | safe}}
    {% endfor %}
  </div>

  </div>


  <div>
  {{form.first_name.label(class="form-label")}}
  {{form.first_name(class="form-control", value=current_user.first_name)}} {# this is the input #}
  {% for error in form.first_name.errors %}
    <small style="color:red;">{{error}}</small>
  {% endfor %}
  </div>

  <div>
  {{form.last_name.label(class="form-label")}}
  {{form.last_name(class="form-control", value=current_user.last_name)}}
  {% for error in form.last_name.errors %}
    <small style="color:red;">{{error}}</small>
  {% endfor %}
  </div>

  <div>
  {{form.email.label(class="form-label")}}
  {{form.email(class="form-control", value=current_user.email)}}
  {% for error in form.email.errors %}
    <small style="color:red;">{{error}}</small>
  {% endfor %}
  </div>


  <br>
  <div>
  {{form.password.label(class="form-label")}}
  {{form.password(class="form-control")}}
  {% for error in form.password.errors %}
    <small style="color:red;">{{error}}</small>
  {% endfor %}
  </div>

  <div>
  {{form.confirm_password.label(class="form-label")}}
  {{form.confirm_password(class="form-control")}}
  {% for error in form.confirm_password.errors %}
    <small style="color:red;">{{error}}</small>
  {% endfor %}
  </div>

  <div>
  {{form.submit(class="btn btn-primary form-control")}}
  </div>

</form>
{% endblock %}